### ISSUE TITLE
No tests for ZFS pool or dataset properties

### ISSUE THREAD

**Issue by ofaaland** [chaos/nodediag#11]
It would be useful to have tests for ZFS pool and dataset properties.  Properties are sometimes changed temporarily for troubleshooting or other maintenance purposes, and we need to confirm they are changed back.  In other cases, the script or person creating a pool or dataset may forget to set a property we want uniformly set.

**Comment by ofaaland** [comment]
@garlick I have some design questions I'd like to discuss with you.

1. Indicating what pools to check
In our particular use case, every pool name is different, and pools may move around due to failover.   For example, jet hosts the file system "lquake", and the pools are named "jet1", "jet2", ... "jet20".  If all the hardware is up and everything is happy, pool "jet1" is imported on host "jet1".  But in a failover scenario that will not be true.

2. Indicating what datasets to check
In our use case, we only want to check the Lustre datasets.  There are other datsets, e.g. the root dataset, whose properties do not matter for our purposes, because they are unused.

So I am thinking of a structure similar to the one used for PCI:
DIAG_ZFS_POOL_NAME[0]=*
DIAG_ZFS_DATASET_NAME[0]=ost1
DIAG_ZFS_RECORDSIZE[0]=1M
DIAG_ZFS_CANMOUNT[0]=no

DIAG_ZFS_POOL_NAME[0]=*
DIAG_ZFS_DATASET_NAME[0]=mdt1
DIAG_ZFS_RECORDSIZE[0]=128K
DIAG_ZFS_CANMOUNT[0]=no

**Comment by garlick** [comment]
Ultimately, I'd say whatever works for you is fine with me.

Any thoughts on how this scheme would work with `nodediag --config`? (Maybe it's OK if that doesn't generate anything for this test).

@elgeoman might have more comments (I haven't played with this stuff in a while)

**Comment by garlick** [comment]
Another thought would be to more rigorously define all possible pools/datasets that are expected to be there, and then explicitly allow some datasets to be missing due to failover (the uncommon case I'm sure for ZFS)

**Comment by ofaaland** [comment]
I just realized that pci.t already does the kind of thing I'm thinking of - DIAG_PCI_SLOT[n] selects a slot, and the other DIAG_PCI_FOO[n] variables set an expected value which must be matched.  So I wouldn't be breaking with standard usage.

> Another thought would be to more rigorously define all possible pools/datasets

I'm not sure how that would look.  Did you have a syntax in mind?

> Any thoughts on how this scheme would work with nodediag --config?

Hm, I'd forgotten about that.  I think it should enumerate the datasets and the supported properties, as is done by pci.t.

**Comment by ofaaland** [comment]
I suppose I could make the property name a selector as well, in which case nodediag --config probably shouldn't do anything.

```
DIAG_ZFS_POOL_NAME[0]=*
DIAG_ZFS_DATASET_NAME[0]=ost1
DIAG_ZFS_PROPERTY_NAME[0]=recordsize
DIAG_ZFS_PROPERTY_VALUE[0]=1M

DIAG_ZFS_POOL_NAME[1]=*
DIAG_ZFS_DATASET_NAME[1]=\(ost1\|mdt1\)
DIAG_ZFS_PROPERTY_NAME[1]=canmount
DIAG_ZFS_PROPERTY_VALUE[1]=off
```

**Comment by garlick** [comment]
> Did you have a syntax in mind?

I was picturing one entry per dataset, with the pool name and dataset name explicit (not wildcards), and then a setting like `DIAG_ZFS_MISSING_R_OK[1]=true` or similar.  Maybe too verbose?

**Comment by ofaaland** [comment]
> I was picturing one entry per dataset, with the pool name and dataset name explicit (not wildcards), and then a setting like DIAG_ZFS_MISSING_R_OK[1]=true or similar. Maybe too verbose?

Yes, that sounds too verbose to me.  52 pools x 6 properties or so to test.  I think it would be cumbersome for the admins to create and maintain, and a lot of duplicate information.

**Comment by garlick** [comment]
Bottom line, I'm fine with whatever you come up with - just make sure it doesn't cause breakage on other systems that run nodediag.

**Comment by ofaaland** [comment]
> Bottom line, I'm fine with whatever you come up with - just make sure it doesn't cause breakage on other systems that run nodediag.

Will do.

Thank you for your feedback!   I'll get Cameron and/or Silva to pipe in.  Feel free to ignore this thread if you like.

**Comment by cmharr** [comment]
Agreed that it wouldn't be tenable to list every pool. We do use a pattern where the pool matches the hostname, so if there were some macro for interpreting that, it could help. The MDT or OST name is then fairly constant, e.g. mdt1 or ost1.

**Comment by ofaaland** [comment]
If I use the name/value pair syntax, then I need to distinguish between pool and dataset properties.

```
DIAG_ZFS_POOL_NAME[0]=*
DIAG_ZFS_DATASET_NAME[0]=ost1
DIAG_ZFS_PROPERTY_TYPE[0]=dataset
DIAG_ZFS_PROPERTY_NAME[0]=recordsize
DIAG_ZFS_PROPERTY_VALUE[0]=1M

DIAG_ZFS_POOL_NAME[1]=*
DIAG_ZFS_DATASET_NAME[1]=\(ost1\|mdt1\)
DIAG_ZFS_PROPERTY_TYPE[1]=dataset
DIAG_ZFS_PROPERTY_NAME[1]=canmount
DIAG_ZFS_PROPERTY_VALUE[1]=off

DIAG_ZFS_POOL_NAME[2]=*
DIAG_ZFS_PROPERTY_TYPE[2]=pool
DIAG_ZFS_PROPERTY_NAME[2]=multihost
DIAG_ZFS_PROPERTY_VALUE[2]=on
```

**Comment by ofaaland** [comment]
> We do use a pattern where the pool matches the hostname, so if there were some macro for interpreting that, it could help. 

That would work for us, now, but fails for other naming conventions - e.g. named after the lustre target, or for >1 target per server, e.g. jet1_1, jet1_2, jet1_3.

What do you think of the example above with recordsize, canmount, and multihost?

**Comment by ofaaland** [comment]
Cameron,
Another option is much less verbose, and so more readable, but also much less flexible - supporting specific properties so each can be assigned a nodediag variable name, like this:
```
DIAG_ZPOOL_NAME[z]=*
DIAG_ZPOOL_AUTOREPLACE[z]="on"
DIAG_ZPOOL_MULTIHOST[z]="on"

DIAG_ZFS_DATASET_NAME[z]="*/mdt1"
DIAG_ZFS_COMPRESSION[z]="on"
DIAG_ZFS_RECORDSIZE[z]="128K"
DIAG_ZFS_DNODESIZE[z]="auto"
DIAG_ZFS_XATTR[z]="sa"
DIAG_ZFS_CANMOUNT[z]="off"

DIAG_ZFS_DATASET_NAME[z]="*/ost1"
DIAG_ZFS_COMPRESSION[z]="on"
DIAG_ZFS_RECORDSIZE[z]="1M"
DIAG_ZFS_DNODESIZE[z]="auto"
DIAG_ZFS_XATTR[z]="sa"
DIAG_ZFS_CANMOUNT[z]="off"
```

**Comment by cmharr** [comment]
That latter option would be acceptable to me.
